// src/utils/listaEquipamentos.ts

export const LISTA_EQUIPAMENTOS = [
  { nome: "Chuveiro Elétrico", potencia: 5500 },
  { nome: "Torneira Elétrica", potencia: 4400 },
  { nome: "Ar-Condicionado 12000 BTUs", potencia: 1200 },
  { nome: "Ar-Condicionado 9000 BTUs", potencia: 900 },
  { nome: "Aquecedor de Ambiente Portátil", potencia: 1500 },
  { nome: "Ventilador de Teto", potencia: 120 },
  { nome: "Ventilador de Coluna", potencia: 80 },
  { nome: "Micro-ondas", potencia: 1200 },
  { nome: "Forno Elétrico", potencia: 2000 },
  { nome: "Cooktop por Indução (4 bocas)", potencia: 7000 },
  { nome: "Geladeira Duplex", potencia: 250 },
  { nome: "Freezer Vertical", potencia: 300 },
  { nome: "Lava-Louças", potencia: 1500 },
  { nome: "Fritadeira Elétrica (Airfryer)", potencia: 1500 },
  { nome: "Sanduicheira / Grill", potencia: 1200 },
  { nome: "Liquidificador", potencia: 600 },
  { nome: "Batedeira", potencia: 400 },
  { nome: "Cafeteira Elétrica", potencia: 1000 },
  { nome: "Espremedor de Frutas", potencia: 200 },
  { nome: "Máquina de Lavar", potencia: 1000 },
  { nome: "Secadora de Roupa", potencia: 2500 },
  { nome: "Lava e Seca (Modo Secagem)", potencia: 2000 },
  { nome: "Ferro de Passar a Vapor", potencia: 1500 },
  { nome: "Aspirador de Pó", potencia: 1400 },
  { nome: "Robô Aspirador", potencia: 40 },
  { nome: 'Televisão LED 55"', potencia: 150 },
  { nome: "Home Theater", potencia: 300 },
  { nome: "Videogame (Console)", potencia: 200 },
  { nome: "Computador Desktop (Gamer)", potencia: 500 },
  { nome: "Notebook", potencia: 65 },
  { nome: "Roteador Wi-Fi", potencia: 15 },
  { nome: "Secador de Cabelo", potencia: 2000 },
  { nome: "Prancha / Chapinha", potencia: 60 },
  { nome: "Bomba de Piscina", potencia: 1500 },
  { nome: "Portão Eletrônico", potencia: 350 },
  { nome: "Lâmpada LED (Unidade)", potencia: 9 },
] as const;
